# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Clean.Architecture.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: '.net build'
  inputs:
    command: 'build'
    projects: 'Clean.Architecture.sln'
    configuration: 'Release'
- task: DotNetCoreCLI@2
  displayName: '.net test'
  inputs:
    command: 'test'
    projects: 'Clean.Architecture.sln'
    configuration: 'Release'
